### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by Agamennon** [spsdco/notes#168]
bugs galore, can't use app (i know this does not help much) on my ubuntu gnome this app is crazy notes are impossible to edit they get garbled, on dropbox all i see is c-0.seed files i cant open

**Comment by chrisdieckhaus** [comment]
I'm having the same issue of it quickly changing back to read only after I start editing.

**Comment by melamity** [comment]
If anyone is still around, there's a issue made at #210 for bugs that should be resolved in Springseed 3.x
