### ISSUE TITLE
Springseed 2 is a mess.

### ISSUE THREAD

**Issue by michealharker** [spsdco/notes#188]
## Uhm, isn't 2.1 after 2? Why 2.0 -> 3?
Springseed 2 is broken. Springseed 2 in general is flawed and broken and shitty and terrible to maintain. We're going to start afresh to bring about a better way for you to take and store notes, online and offline.

## Why Springseed 3 over Evernote?
We're working on features. We've got this feature set we're hoping to implement sometime in 3.x:

**General Improvements**
 - Mobile and Web Version
 - Distractionless Writing (So it can be used as a Markdown Editor)
 - Better Editor
 - Todos / Reminders
 - Publish Online
 - Draw Notes
 - OMG! SYNCING THAT ACTUALLY WORKS!!1!!one!11!!!eleven!!

**Work Better**

 - Sharing
 - Comments
 - Collaboration
 - Teams

We're also working on splitting this repo into Web, Desktop and Mobile, and provide a way for all these different packages to communicate using an API or something similar like that.

## Design

Yep. I quickly designed the desktop version using Gliffy very quickly. This might be possible with some native APIs, give or take some issues maybe with the side menu. Maybe this could be done in Qt, which helps with compatibility across Operating Systems? Take 'Telegram Desktop' for example.

![springseed3](https://cloud.githubusercontent.com/assets/939805/6741620/00d259d4-ce81-11e4-8959-02f25c989b93.png)

**Comment by nitishch** [comment]
+1 for Qt

**Comment by michealharker** [comment]
Almost two months later and I feel a little more prepared to work on this however the backend API I am planning needs to be done before we consider doing the web version (and then the desktop versions).

Just going to mention, this project isn't abandoned and still being worked on. Here's a list of what needs doing in the backend for this to work out:

## Old Features
- [ ] Login
- [ ] Notebooks
- [ ] Notes

## New Features
- [ ] Collaboration Protocol(?)
- [ ] Publishing Notes
- [ ] Comments
- [ ] Teams / Sharing

**Comment by addisonamiri** [comment]
Has there been thought to using Github's Electron for the gui? It'd be cross platform and if you write some fancy CSS it could even be it's own mobile version. I'm the last one to jump on the JS-everywhere bandwagon but this seems like a option to consider.

**Comment by michealharker** [comment]
Version 2 was written in Electron and JS, however the codebase wasn't really created for Electron so I initially thought against using it (because it caused some bugs switching from nw.js) - however I could try using Electron again, sounds like a decent idea.

**Comment by addisonamiri** [comment]
I've spent the past hour looking into markdown live previews and I've found [markdown-live](https://github.com/mobily/markdown-live) which can do it and it even has the current directory in a sidebar. It could be a pretty good starting point if you just want fiddle around with it and see what happens. It might take a bit of work ripping out all the socket.io stuff for browser rendering though. It's also MIT licensed so if you end up liking what you create it shouldn't be a problem.

**Comment by hollowdoor** [comment]
@michealharker
Have you decided what direction you're going to take? Electron, or Qt?

**Comment by Lanzafame** [comment]
@michealharker 
Would love an update? Am keen to assist with 3.0

**Comment by Xtrinity** [comment]
I'm writing a cross-platform multi-purpose application that is inspired/based off of the old SpringSeed design. I'm calling it Sprout and it should have a working version with all of the original core features of SpringSeed besides Dropbox done by the next week or so. Most of the issues like not being able to add more notes should not affect Sprout as it is built under a different platform. If anyone is interested let me know.

@michealharker I'm chilling in #springseed on freenode. I've tried shooting you a couple messages but you haven't responded. If you would like to collaborate or want to talk i'll be sticking around in the channel for a couple of more days.

**Comment by hollowdoor** [comment]
@Xtrinity What are you coding Sprout in?

**Comment by Xtrinity** [comment]
@hollowdoor It's going to be coded in Java and OpenGL. As issues arise for performance i'm planning to use JNI. I haven't uploaded my work so far but the project's GitHub can be found at https://github.com/SproutOne/Sprout

**Comment by hollowdoor** [comment]
@Xtrinity Too bad. I terribly dislike Java. If you were using javascript, or c maybe I'd contribute. Well I might download and try it once you get to a release. :)

**Comment by InsidiousMind** [comment]
I'm assuming this whole project is dead?

**Comment by zackp30** [comment]
@InsidiousMind Unfortunately, for now, @michealharker is very busy with work, and I'm busy with GCSEs. Sorry.

**Comment by michealharker** [comment]
Work on Springseed 3 is being done, but slowly because I have a lot less
free time :) I should be doing some significant work in December and
getting on track to try and get something out for March/April 2016. No
promises.
