### ISSUE TITLE
springseed.zip is not available any more

### ISSUE THREAD

**Issue by n2o** [spsdco/notes#200]
Requests to http://assets.apertron.net/springseed.zip result in a 404.

This source is needed to build springseed with the [Arch User Repository](https://aur.archlinux.org/packages/springseed/)

**Comment by zackp30** [comment]
Whoops! Sorry. I forgot how it was laid out, do you have a copy of an old version of the file? I'll reconstruct it from the latest version.

**Comment by zackp30** [comment]
(I maintain apertron.net)

**Comment by n2o** [comment]
No, I don't know how this file looked like. It must be different from the zipped 2.0 version on Github (different hash and it actually does not work if I just change the source in the PKDBUILD file from Arch).

Building it on my own ends in some errors... I can open a separate Issue for this. Hoped you could reupload the file and the building tool from Arch gets the rest of the work done :-)

**Comment by zackp30** [comment]
Damn, I've unfortunately lost the file while cleaning up things on the server. Mind creating a new issue concerning the build errors? Sorry about this.

**Comment by n2o** [comment]
Okay, I will retry the manual installation process in the next days. Thanks for your help!

**Comment by ryonsherman** [comment]
Arch PKGBUILD maintainer here. I happened to still have a backup of the archive in my build directory.

https://dl.dropboxusercontent.com/u/6830281/springseed.zip
SHA256: e6a47b92e27e2f4ec4192e49f3c15b50a13067a1a855b59dc8744e1eae7caa90

For the sake of basic integrity, this hash matches the one seen in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=springseed) in the AUR.

**Comment by n2o** [comment]
Awesome, thank you. Now @zackp30 only needs to reupload it. Or we host this file directly on Github...?
Maybe this is the better solution.

I would not have trusted your zip file without the correct hash ;-)

**Comment by zackp30** [comment]
Damn! Forgot about this, sorry, downloading now.

**Comment by zackp30** [comment]
Reuploaded.

**Comment by zackp30** [comment]
Thanks @ryonsherman!

**Comment by zackp30** [comment]
```
gpg --recv-keys 694C308D --keyserver pgp.mit.edu
wget http://assets.apertron.net/springseed.zip http://assets.apertron.net/springseed.zip.asc
gpg --verify springseed.zip.asc
```

**Comment by ryonsherman** [comment]
The archive seems to be unavailable again:

```
--2016-05-16 15:36:54--  http://assets.apertron.net/springseed.zip
Resolving assets.apertron.net (assets.apertron.net)... 94.23.236.101
Connecting to assets.apertron.net (assets.apertron.net)|94.23.236.101|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://assets.apertron.net/springseed.zip [following]
--2016-05-16 15:36:54--  https://assets.apertron.net/springseed.zip
Connecting to assets.apertron.net (assets.apertron.net)|94.23.236.101|:443... connected.
WARNING: no certificate subject alternative name matches
    requested host name ‘assets.apertron.net’.
HTTP request sent, awaiting response... 404 Not Found
2016-05-16 15:36:54 ERROR 404: Not Found.
```

**Comment by zackp30** [comment]
Dammit, I thought I had forgotten something: https://xack.xyz/misc/springseed.zip

**Comment by melamity** [comment]
Duplicate #209
